# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0103fa8df0f7de26e2359bf6e703b7fe502c097c6b831db9d21c1dfd1060b84910eb3ac6b0ff36299ddaf80580bab00be832e544d25d5d92bc5386b40c9904c9

test:
  secret_key_base: 776983379291f976802d2e8d1e27dd908053b789cd3fd64368b581a730ce3f09496a07e67b48d24d473d6eeeae919cdc9b29450fd8fb9cb201cfae3e8cfd9b8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
